// apps/www/src/components/content/component-preview/preview.tsx
import { RotateCcw } from "lucide-react"
import * as React from "react"

import { Button } from "@ui/react/button"
import Examples from "@ui/react/examples"

import { Icons } from "@/components/icons"
interface Props {
  name: string
  hidden?: boolean
}

export default function Preview({ name, hidden }: Props) {
  if (hidden) return null

  const [key, setKey] = React.useState(0)
  const Component = React.lazy(Examples[name])

  return (
    <div
      key={key}
      className="relative flex size-full flex-1 items-center justify-center p-4 md:p-10"
    >
      <Button
        onClick={() => setKey((prev) => prev + 1)}
        variant="ghost"
        className="absolute top-2 right-2"
      >
        <RotateCcw aria-label="restart-btn" size={16} />
      </Button>
      <React.Suspense
        fallback={
          <div className="flex w-full items-center justify-center text-muted-foreground text-sm">
            <Icons.spinner className="mr-2 h-4 w-4 animate-spin" />
            Loading...
          </div>
        }
      >
        <Component />
      </React.Suspense>
    </div>
  )
}

// apps/www/src/components/content/component-preview/preview.vue
<script setup lang="ts">
import { Button } from "@ui/vue/button"
import Examples from "@ui/vue/examples"
import { RotateCcw } from "lucide-vue-next"
import { Suspense, defineAsyncComponent, ref } from "vue"

const props = defineProps<{
  name: string
  hidden: boolean
}>()

const key = ref(0)

const Component = defineAsyncComponent(
  props.hidden ? () => Promise.resolve() : Examples[props.name]
)
</script>

<template>
  <div
    :key="key"
    v-if="!hidden"
    class="relative flex size-full flex-1 items-center justify-center p-4 md:p-10"
  >
    <Button
      @click="() => key += 1"
      variant="ghost"
      class="absolute top-2 right-2"
    >
      <RotateCcw aria-label="restart-btn" :size="16" />
    </Button>
    <Suspense>
      <Component />
    </Suspense>
  </div>
</template>
